Repository tanem/svg-injector, pull requests merged in 2021-07, with the labels that each got.

#798 Update CI workflow & fix karma config
  .github/workflows/ci.yml
  karma.conf.js
Labels: internal

#799 Update CI workflow
  .github/workflows/ci.yml
Labels: internal, safe to test

#793 Add httpRequestWithCredentials option
  README.md
  examples/api-usage/index.ts
  examples/basic-usage/package-lock.json
  src/inject-element.ts
  src/load-svg-cached.ts
  src/load-svg-uncached.ts
  src/make-ajax-request.ts
  src/svg-injector.ts
Labels: enhancement, safe to test

#800 Update tanem-scripts
  package-lock.json
  package.json
Labels: internal

#801 CI workflow tweaks
  .github/workflows/ci.yml
Labels: internal
